services:
  - type: web
    name: eduvillage-frontend
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_BASE_URL
        value: https://eduvillage-backend-5.onrender.com
    publicDir: dist
